services:
  postgres_db:
    image: postgres:18-alpine
    container_name: postgres_database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pest-bin
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
    networks:
      - pestben-network

networks:
  pestben-network:
    name: pestben-network
    driver: bridge